// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "ordinals.proto" (package "ordinals", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ordinals.OutPoint
 */
export interface OutPoint {
    /**
     * @generated from protobuf field: bytes hash = 1;
     */
    hash: Uint8Array;
    /**
     * @generated from protobuf field: uint32 vout = 2;
     */
    vout: number;
}
/**
 * @generated from protobuf message ordinals.SatRange
 */
export interface SatRange {
    /**
     * @generated from protobuf field: uint64 start = 1;
     */
    start: bigint;
    /**
     * @generated from protobuf field: uint64 distance = 2;
     */
    distance: bigint;
}
/**
 * @generated from protobuf message ordinals.SatRanges
 */
export interface SatRanges {
    /**
     * @generated from protobuf field: repeated ordinals.SatRange ranges = 1;
     */
    ranges: SatRange[];
}
/**
 * @generated from protobuf message ordinals.SatRangesRequest
 */
export interface SatRangesRequest {
    /**
     * @generated from protobuf field: ordinals.OutPoint outpoint = 1;
     */
    outpoint?: OutPoint;
}
/**
 * @generated from protobuf message ordinals.SatRangesResponse
 */
export interface SatRangesResponse {
    /**
     * @generated from protobuf field: ordinals.SatRanges satranges = 1;
     */
    satranges?: SatRanges;
}
/**
 * @generated from protobuf message ordinals.SatRequest
 */
export interface SatRequest {
    /**
     * @generated from protobuf field: uint64 sat = 1;
     */
    sat: bigint;
}
/**
 * @generated from protobuf message ordinals.SatResponse
 */
export interface SatResponse {
    /**
     * @generated from protobuf field: uint64 pointer = 1;
     */
    pointer: bigint;
    /**
     * @generated from protobuf field: ordinals.SatRange satrange = 2;
     */
    satrange?: SatRange;
    /**
     * @generated from protobuf field: ordinals.OutPoint outpoint = 3;
     */
    outpoint?: OutPoint;
    /**
     * @generated from protobuf field: ordinals.SatRanges satranges = 4;
     */
    satranges?: SatRanges;
}
// @generated message type with reflection information, may provide speed optimized methods
class OutPoint$Type extends MessageType<OutPoint> {
    constructor() {
        super("ordinals.OutPoint", [
            { no: 1, name: "hash", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "vout", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<OutPoint>): OutPoint {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hash = new Uint8Array(0);
        message.vout = 0;
        if (value !== undefined)
            reflectionMergePartial<OutPoint>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OutPoint): OutPoint {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes hash */ 1:
                    message.hash = reader.bytes();
                    break;
                case /* uint32 vout */ 2:
                    message.vout = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OutPoint, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes hash = 1; */
        if (message.hash.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.hash);
        /* uint32 vout = 2; */
        if (message.vout !== 0)
            writer.tag(2, WireType.Varint).uint32(message.vout);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ordinals.OutPoint
 */
export const OutPoint = new OutPoint$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SatRange$Type extends MessageType<SatRange> {
    constructor() {
        super("ordinals.SatRange", [
            { no: 1, name: "start", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "distance", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<SatRange>): SatRange {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.start = 0n;
        message.distance = 0n;
        if (value !== undefined)
            reflectionMergePartial<SatRange>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SatRange): SatRange {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 start */ 1:
                    message.start = reader.uint64().toBigInt();
                    break;
                case /* uint64 distance */ 2:
                    message.distance = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SatRange, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 start = 1; */
        if (message.start !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.start);
        /* uint64 distance = 2; */
        if (message.distance !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.distance);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ordinals.SatRange
 */
export const SatRange = new SatRange$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SatRanges$Type extends MessageType<SatRanges> {
    constructor() {
        super("ordinals.SatRanges", [
            { no: 1, name: "ranges", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SatRange }
        ]);
    }
    create(value?: PartialMessage<SatRanges>): SatRanges {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ranges = [];
        if (value !== undefined)
            reflectionMergePartial<SatRanges>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SatRanges): SatRanges {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated ordinals.SatRange ranges */ 1:
                    message.ranges.push(SatRange.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SatRanges, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated ordinals.SatRange ranges = 1; */
        for (let i = 0; i < message.ranges.length; i++)
            SatRange.internalBinaryWrite(message.ranges[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ordinals.SatRanges
 */
export const SatRanges = new SatRanges$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SatRangesRequest$Type extends MessageType<SatRangesRequest> {
    constructor() {
        super("ordinals.SatRangesRequest", [
            { no: 1, name: "outpoint", kind: "message", T: () => OutPoint }
        ]);
    }
    create(value?: PartialMessage<SatRangesRequest>): SatRangesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SatRangesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SatRangesRequest): SatRangesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ordinals.OutPoint outpoint */ 1:
                    message.outpoint = OutPoint.internalBinaryRead(reader, reader.uint32(), options, message.outpoint);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SatRangesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ordinals.OutPoint outpoint = 1; */
        if (message.outpoint)
            OutPoint.internalBinaryWrite(message.outpoint, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ordinals.SatRangesRequest
 */
export const SatRangesRequest = new SatRangesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SatRangesResponse$Type extends MessageType<SatRangesResponse> {
    constructor() {
        super("ordinals.SatRangesResponse", [
            { no: 1, name: "satranges", kind: "message", T: () => SatRanges }
        ]);
    }
    create(value?: PartialMessage<SatRangesResponse>): SatRangesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SatRangesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SatRangesResponse): SatRangesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ordinals.SatRanges satranges */ 1:
                    message.satranges = SatRanges.internalBinaryRead(reader, reader.uint32(), options, message.satranges);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SatRangesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ordinals.SatRanges satranges = 1; */
        if (message.satranges)
            SatRanges.internalBinaryWrite(message.satranges, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ordinals.SatRangesResponse
 */
export const SatRangesResponse = new SatRangesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SatRequest$Type extends MessageType<SatRequest> {
    constructor() {
        super("ordinals.SatRequest", [
            { no: 1, name: "sat", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<SatRequest>): SatRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sat = 0n;
        if (value !== undefined)
            reflectionMergePartial<SatRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SatRequest): SatRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 sat */ 1:
                    message.sat = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SatRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 sat = 1; */
        if (message.sat !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.sat);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ordinals.SatRequest
 */
export const SatRequest = new SatRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SatResponse$Type extends MessageType<SatResponse> {
    constructor() {
        super("ordinals.SatResponse", [
            { no: 1, name: "pointer", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "satrange", kind: "message", T: () => SatRange },
            { no: 3, name: "outpoint", kind: "message", T: () => OutPoint },
            { no: 4, name: "satranges", kind: "message", T: () => SatRanges }
        ]);
    }
    create(value?: PartialMessage<SatResponse>): SatResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pointer = 0n;
        if (value !== undefined)
            reflectionMergePartial<SatResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SatResponse): SatResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 pointer */ 1:
                    message.pointer = reader.uint64().toBigInt();
                    break;
                case /* ordinals.SatRange satrange */ 2:
                    message.satrange = SatRange.internalBinaryRead(reader, reader.uint32(), options, message.satrange);
                    break;
                case /* ordinals.OutPoint outpoint */ 3:
                    message.outpoint = OutPoint.internalBinaryRead(reader, reader.uint32(), options, message.outpoint);
                    break;
                case /* ordinals.SatRanges satranges */ 4:
                    message.satranges = SatRanges.internalBinaryRead(reader, reader.uint32(), options, message.satranges);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SatResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 pointer = 1; */
        if (message.pointer !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.pointer);
        /* ordinals.SatRange satrange = 2; */
        if (message.satrange)
            SatRange.internalBinaryWrite(message.satrange, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* ordinals.OutPoint outpoint = 3; */
        if (message.outpoint)
            OutPoint.internalBinaryWrite(message.outpoint, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* ordinals.SatRanges satranges = 4; */
        if (message.satranges)
            SatRanges.internalBinaryWrite(message.satranges, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ordinals.SatResponse
 */
export const SatResponse = new SatResponse$Type();
